version: "3.7"

services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    environment:
      COLLECTIONS: "crowdsecurity/nginx crowdsecurity/whitelist-good-actors crowdsecurity/base-http-scenarios crowdsecurity/mysql"
    ports:
      - "6060:6060"
      - "8080:8080"
    volumes:
      - "./data:/var/lib/crowdsec/data"
      #- "./config/config.yaml:/etc/crowdsec/config.yaml:rw"
      - "./config/acquis.yaml:/etc/crowdsec/acquis.yaml:ro"
      - "./logs:/tmp/logs/:ro"
    
  web:
    image: nginx
    ports:
      - "9090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
      - ./logs/nginx:/var/log/nginx/:rw
    
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: gfBkNjGcD2HURPfxbMiGm2XciiGRbyz55KLjXx4QCXw3CuyWVChKWr3bWYu6yjwrREu4kbFfRmEMtG79S7X22MgDx
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: gfBkNjGcD2HURPfxbMiGm2XciiGRbyz55KLjXx4QCXw3CuyWVChKWr3bWYu6yjwrREu4kbFfRmEMtG79S7X22MgDx
    volumes:
      - ./logs/mysql:/tmp/mysql/:rw
    ports:
      - "3306:3306"
    command: mysqld --log-error=/tmp/mysql/error.log --general-log=1 --general-log-file=/tmp/mysql/general.log

  